# Generated by Django 5.2.7 on 2025-11-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0003_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
